services:
  - type: web
    name: alx-project-nexus
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python create_superuser.py
    startCommand: gunicorn polls_backend.wsgi
